import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
    },
    inner: {
        flex: 1,
    },
    centerContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#fff",
    },
    title: {
        fontSize: 28,
        fontWeight: "700",
        color: "#208AEF",
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 16,
        color: "#666",
        marginBottom: 32,
    },
    googleButton: {
        backgroundColor: "#208AEF",
        paddingHorizontal: 32,
        paddingVertical: 14,
        borderRadius: 8,
    },
    googleButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
    // Header bar
    headerBar: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: "#e0e0e0",
        backgroundColor: "#fff",
        gap: 12,
    },
    hamburger: {
        fontSize: 22,
        color: "#333",
    },
    appName: {
        fontSize: 18,
        fontWeight: "600",
        color: "#000",
        flex: 1,
    },
    logo: {
        width: 20,
        height: 20,
    },
    avatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
    },
    avatarPlaceholder: {
        backgroundColor: "#208AEF",
        alignItems: "center",
        justifyContent: "center",
    },
    avatarText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "700",
    },
    menuOverlay: {
        ...StyleSheet.absoluteFill,
        justifyContent: "flex-start",
        alignItems: "flex-end",
        zIndex: 50,
    },
    menuContainer: {
        backgroundColor: "#fff",
        borderRadius: 12,
        width: 240,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 2,
    },
    menuAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
    },
    menuAvatarText: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "700",
    },
    menuInfo: {
        padding: 16,
        gap: 4,
    },
    menuName: {
        fontSize: 15,
        fontWeight: "600",
        color: "#333",
    },
    menuEmail: {
        fontSize: 12,
        color: "#888",
        marginTop: 2,
    },
    menuDivider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: "#e0e0e0",
    },
    menuItem: {},
    menuItemText: {
        fontSize: 15,
        color: "#333",
    },
    menuItemTextDanger: {
        fontSize: 15,
        color: "#e74c3c",
    },
    menuActions: {
        paddingVertical: 16,
        paddingHorizontal: 16,
        gap: 16,
    },
    // Notes list
    list: {
        flex: 1,
    },
    listContent: {
        padding: 16,
        gap: 10,
        flexGrow: 1,
    },
    loader: {
        marginTop: 40,
    },
    emptyText: {
        textAlign: "center",
        color: "#999",
        fontSize: 15,
        marginTop: 40,
    },
    fab: {
        position: "absolute",
        right: 20,
        bottom: 20,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: "#208AEF",
        alignItems: "center",
        justifyContent: "center",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    fabText: {
        fontSize: 28,
        color: "#fff",
        lineHeight: 30,
    },
    emptyText: {
        textAlign: "center",
        color: "#999",
        fontSize: 15,
        marginTop: 40,
    },
    fab: {
        position: "absolute",
        right: 20,
        bottom: 20,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: "#208AEF",
        alignItems: "center",
        justifyContent: "center",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    // Prompt modal
    pickerOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.3)",
        justifyContent: "center",
        alignItems: "center",
    },
    promptContainer: {
        backgroundColor: "#fff",
        borderRadius: 12,
        width: 280,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 8,
    },
    promptTitle: {
        fontSize: 17,
        fontWeight: "600",
        color: "#333",
        marginBottom: 14,
    },
    promptInput: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 8,
        padding: 10,
        fontSize: 15,
        color: "#333",
        marginBottom: 16,
    },
    promptButtons: {
        flexDirection: "row",
        justifyContent: "flex-end",
        gap: 10,
    },
    promptCancel: {
        paddingVertical: 8,
        paddingHorizontal: 16,
    },
    promptCancelText: {
        fontSize: 15,
        color: "#666",
    },
    promptConfirm: {
        backgroundColor: "#208AEF",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
    },
    promptConfirmText: {
        fontSize: 15,
        color: "#fff",
        fontWeight: "600",
    },
    colorRow: {
        flexDirection: "row",
        gap: 10,
        marginBottom: 16,
    },
    colorDot: {
        width: 28,
        height: 28,
        borderRadius: 14,
    },
    colorDotSelected: {
        borderWidth: 3,
        borderColor: "#333",
    },
});
